name: rodrigodealvarenga
favicon: null
layout_spectrum: 0
typography_spectrum: 0.21152
title: Rodrigo de Alvarenga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0c17'
    - '#403c39'
    - '#fefefe'
    - '#858388'
    - '#cccbd3'
  brandStrength: 0
  lightness: 0.42532858857885003
  saturation: 0.836241363780573
  rhythmicContrast: 0.29733997909352183
purpose: []
