name: rodrigodealvarenga
favicon: null
layout_spectrum: 0.64064
typography_spectrum: 0.4176860172301531
title: Rodrigo de Alvarenga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08070d'
    - '#d7ccae'
    - '#fdf8e6'
    - '#8e6247'
    - '#243946'
  brandStrength: 0.9224291583523154
  lightness: 0.42532858857885003
  saturation: 0.836241363780573
  rhythmicContrast: 0.29733997909352183
purpose: []
